spring.application.name=blogApplication

# Database Configuration - Using Environment Variables
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/blog_application}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Password@2026}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration - Using Environment Variables
spring.app.jwtSecret=${JWT_SECRET:mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm}
spring.app.jwtExpirationMs=${JWT_EXPIRATION:3000000}