spring.application.name=blogApplication

#spring.datasource.url=jdbc:postgresql://localhost:5432/blog_application
#spring.datasource.username=postgres
#spring.datasource.password=Password@2026
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://dpg-d8nf7n8js32c73dlfnhg-a.virginia-postgres.render.com:5432/blog_application_z3x4
spring.datasource.username=blog_application_z3x4_user
spring.datasource.password=a88w69oyhuMy2ZiRkGXwkH7ZnmrKt43I
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000